.PHONY: clean All

All:
	@echo "----------Building project:[ Test - Release ]----------"
	@cd "CPP_workspace" && "$(MAKE)" -f  "Test.mk"
clean:
	@echo "----------Cleaning project:[ Test - Release ]----------"
	@cd "CPP_workspace" && "$(MAKE)" -f  "Test.mk" clean
